"""Subclass of mainFrame, which is generated by wxFormBuilder."""

import wx
import interface
import datetime
from models import snackk

# Implementing mainFrame
class createFrameSnack( interface.createSnackFrame ):
    def __init__( self ):
        interface.createSnackFrame.__init__(self, parent=None)
        self.snackModel = snackk.Snack()
        self.id = None

    def setId(self, id):
        self.id = id

    def setNamaSnack(self, nama_snack):
        self.textCtrlNamaSnack.SetValue(nama_snack)

    def setStock(self, stock_snack):
        self.textCtrlStock.SetValue(str(int))

    def setHarga(self, harga_snack):
        self.textCtrlHargaSnack.SetValue(str(int))


    def handleBtnSaveSnack(self, event):
        nama_snack = self.textCtrlNamaSnack.GetValue().strip()
        stock_snack = self.textCtrlStock.GetValue().strip()
        harga_snack = self.textCtrlHargaSnack.GetValue().strip()

        try:
            if self.id == None:
                result = self.snackModel.insert(values=[nama_snack, stock_snack, harga_snack], columns=['nama_snack', 'stock_snack', 'harga_snack'])
            else:
                result = self.snackModel.update(colValues={'nama_snack': nama_snack, 'Stock': stock_snack, 'harga_snack': harga_snack, }, identifierValue=self.id)

        except Exception as err:
            wx.MessageDialog(None, str(err), 'An error occured.', style=wx.OK | wx.ICON_ERROR).ShowModal()

        finally:
            if self.id == None:
                wx.MessageDialog(None, 'New snack successfully added.', 'Success', style=wx.OK | wx.ICON_INFORMATION).ShowModal()
            else:
                wx.MessageDialog(None, 'Food data has been updated.', 'Update Success', style=wx.OK | wx.ICON_INFORMATION).ShowModal()