"""Subclass of mainFrame, which is generated by wxFormBuilder."""

import wx
import interface
import datetime
from models import foodd

# Implementing mainFrame
class createFrameFood( interface.createMakananFrame ):
    def __init__( self ):
        interface.createMakananFrame.__init__(self, parent=None)
        self.foodModel = foodd.Food()
        self.id = None

    def setId(self, id):
        self.id = id

    def setNamaMakanan(self, nama_makanan):
        self.textCtrlNamaMakanan.SetValue(nama_makanan)

    def setStock(self, stock_makanan):
        self.textCtrlStock.SetValue(str(int))

    def setHarga(self, harga_makanan):
        self.textCtrlHargaMakanan.SetValue(str(int))


    def handleBtnSaveMakanan(self, event):
        nama_makanan = self.textCtrlNamaMakanan.GetValue().strip()
        stock_makanan = self.textCtrlStock.GetValue().strip()
        harga_makanan = self.textCtrlHargaMakanan.GetValue().strip()

        try:
            if self.id == None:
                result = self.foodModel.insert(values=[nama_makanan, stock_makanan, harga_makanan], columns=['nama_makanan', 'stock_makanan', 'harga_makanan'])
            else:
                result = self.foodModel.update(colValues={'nama_makanan': nama_makanan, 'stock_makanan': stock_makanan, 'harga_makanan': harga_makanan, }, identifierValue=self.id)

        except Exception as err:
            wx.MessageDialog(None, str(err), 'An error occured.', style=wx.OK | wx.ICON_ERROR).ShowModal()

        finally:
            if self.id == None:
                wx.MessageDialog(None, 'New food successfully added.', 'Success', style=wx.OK | wx.ICON_INFORMATION).ShowModal()
            else:
                wx.MessageDialog(None, 'Food data has been updated.', 'Update Success', style=wx.OK | wx.ICON_INFORMATION).ShowModal()